import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
const [state, setstate] = useState()

  const Change = (e) => {
      setstate(e.target.value)
  }
  function Click(e) {
    e.preventDefault()

const form = document.querySelector("#send")
form.action = `http://localhost:3000/post/${state}`

    fetch("http://localhost:3000/api/hello", {
      method:'POST',
      body:JSON.stringify(state)
    })
    .then(response => response.json())
     
  }

return  (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form action='/api/hello' id='send' onSubmit={Click}>
        <input type="text" name="query" onChange={Change}/>
        <button>Send</button>
      </form>
     </>
  )
}
